routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use Illuminate\Foundation\Auth\AuthenticatesUsers;

//for admin controller
Route::get('/login', function () {
    return view('/auth/login');
});


Auth::routes(['verify' => true]);

Route::get('/home', 'HomeController@index')->name('home')->middleware('verified');
Route::post('/sendSMS','SendSMSController@store')->middleware('auth')->middleware('verified');
Route::post('/getBalance','SendSMSController@getBalance')->middleware('auth')->middleware('verified');
Route::get('/demo','DemoController@index')->middleware('auth')->middleware('verified');
Route::prefix('/admin')->middleware(['auth','verified'])->group(function () {
	Route::resource('/module','ModuleController',['expect'=>['show']]);
	Route::resource('/submodule','SubModuleController');
	Route::resource('/organizationdetail','OrganizationDetailController');
	Route::resource('/menusetup','MenuSetupController');
	Route::resource('/submenusetup','SubMenuSetupController');
	Route::resource('/usersetup', 'UserSetupController');
	Route::get('/changepassword/create','UserSetupController@changepasswordcreate');
	Route::get('/changepassword','UserSetupController@changepassword')->name('usersetup.changepassword');
	Route::resource('/footercontactsetup','FooterContactSetupController');
	Route::resource('/quicklinksetup','QuickLinkSetupController');
	Route::resource('/socialmediaicon','SocialMediaIconController');
	Route::resource('/slidersetup','SliderSetupController');
	Route::resource('/noticesetup','NoticeSetupController');
	Route::resource('/aboutus','AboutUsController');
	Route::resource('/service','ServiceController');
	Route::resource('/counter','CounterSetupController');
	Route::resource('/timetable','TimeTableController');
	Route::resource('/membermessage','MemberSetupController');
	Route::resource('/eventsetup','EventSetupController');
	Route::resource('/partner','PartnerController');
	Route::resource('/gallery','GalleryController');
	Route::resource('/testimonial','TestimonialController');
	Route::get('/gallery/album/{id}','GalleryController@intoAlbum');
	Route::post('/gallery/upload/store','GalleryController@fileStore')->name('users.fileupload');
	Route::get('/image/delete','GalleryController@fileDestroy');
	Route::get('/delete/image/{id}/{albumid}','GalleryController@deleteImage');
	Route::resource('/class','ClassesController');
	Route::resource('/section','SectionController');
	Route::resource('/subject','SubjectController');
	Route::resource('/lessonentity','LessonEntityController');
	Route::resource('/lessondetail','LessondetailController');
	Route::resource('/lesson','LessonController');
	Route::get('/getsubject','LessonController@getsubject');
	Route::get('/getlesson','LessonController@getlesson');
	Route::resource('/student','StudentController');
	Route::get('/getsection','StudentController@getsection');
});


//for frontend controller
Route::get('/','FrontEndController@index');
Route::get('/aboutus','FrontEndController@aboutus');
Route::get('/classes','FrontEndController@classes');
Route::get('/classes-timetable','FrontEndController@classestimetable');
Route::get('/services','FrontEndController@services');
Route::get('/ourteam','FrontEndController@ourteam');
Route::get('/contact','FrontEndController@contact');
Route::post('/contact','FrontEndController@sendmail');
Route::get('/ourblog','FrontEndController@ourblog');
Route::get('/gallery','FrontEndController@gallery');
Route::get('/bmi-calculator','FrontEndController@bmicalculator');
Route::post('/testimonial','FrontEndController@testimonial');

app/SubModule.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class SubModule extends Model
{
    protected $table='submodules';
    public $timestamps=false;
    protected $primaryKey='submoduleid';
    public function users()
	{
		return $this->belongsToMany('App\User','usersubmodules','id','submoduleid');
	}
}

app/Http/Controllers/SubModuleController.php
<?php

namespace App\Http\Controllers;

use App\SubModule;
use App\Module;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Session;
use DB;

class SubModuleController extends Controller
{
   public function __construct()
    {
       $this->middleware(['auth', 'verified']);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $submodule=DB::table('submodules as sm')
            ->join('modules as md', 'sm.moduleid', '=', 'md.moduleid')
            ->select('sm.*', 'md.modulename')
            ->paginate(10);
        $modules=Module::all();
        return view('admin/submodules/index',compact('submodule','modules'));
    }


    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $uniquesubmodule=SubModule::where([['submodulename', '=', $request->submodulename],['moduleid', '=', $request->moduleid]])->get();

        $uniqueurl=SubModule::where([['url', '=', $request->submoduleurl],['moduleid', '=', $request->moduleid]])->get();
        
        if(count($uniquesubmodule)!=0)
        {
            $validator = Validator::make($request->all(), [
                        'submodulename'=>'required|min:3||unique:submodules,submodulename',
                        ]);

            if ($validator->fails()) {
                
                Session::flash('error',"submodule name have to be unique!!");
                return redirect()->back();
            }
        }
        elseif(count($uniqueurl)!=0)
        {
            $validator = Validator::make($request->all(), [
                         'submoduleurl'=>'required|unique:submodules,url'
                        ]);

            if ($validator->fails()) {
                
                Session::flash('error',"submodule url have to be unique!!");
                return redirect()->back();
            }
        }

        else
        {
            $validator = Validator::make($request->all(), [
                            'submodulename'=>'required',
                            'submoduleorder'=>'required',
                        ]);

            if ($validator->fails()) {
                
                Session::flash('error',"submodule name and submodule order required!!");
                return redirect()->back();
            }
        }

        $submodule=new SubModule;
        $submodule->submoduleid=getMaxId('submodules','submoduleid');
        $submodule->moduleid=$request->moduleid;
        $submodule->submodulename=$request->submodulename;
        $submodule->url=$request->submoduleurl;
        $submodule->submoduleorder=$request->submoduleorder;
        $submodule->save();
        Session::flash('msg',"Sub Module Added Successfully.");
        return redirect()->back();
    }


    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\SubModule  $subModule
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $submoduleid)
    {
        $submodule=SubModule::where('submoduleid', $submoduleid)->first();
        //validation form modulename
        if($request->submodulename == $submodule->submodulename)
        {
            $validator = Validator::make($request->all(), [
                          'submodulename'=>'required'
                        ]);

            if ($validator->fails()) {
                
                Session::flash('error',"Submodule Name required !!");
                return redirect()->back();
            }
        }
        elseif ($request->submoduleorder==$submodule->submoduleorder) {
            $validator = Validator::make($request->all(), [
                          'submoduleorder'=>'required'
                        ]);

            if ($validator->fails()) {
                
                Session::flash('error',"Submodule Order required !!");
                return redirect()->back();
            }
        }
         elseif($request->submoduleurl!=$submodule->url)
        {
           $validurl=DB::select('select * from submodules where moduleid='. $request->moduleid . ' and url= "'.$request->submoduleurl.'"');

            if(count($validurl)!=0)
            {
                $validator = Validator::make($request->all(), [
                          'submoduleurl'=>'required|unique:submodules,url'
                        ]);

                if ($validator->fails()) {
                    Session::flash('error',"Submodule url have to be unique !!");
                    return redirect()->back();
                }
             
            }
            else
            {
                $validator = Validator::make($request->all(), [
                          'submoduleurl'=>'required'
                        ]);

                if ($validator->fails()) {
                    
                    Session::flash('error',"Submodule url required !!");
                    return redirect()->back();
                }
            }

        }  
        else
        {
           $validsubmodule=DB::select("select * from submodules where moduleid=".$request->moduleid ." and submodulename=".$request->submodulename);

            if(count($validsubmodule)!=0)
            {
                $validator = Validator::make($request->all(), [
                            'submoduleorder'=>'required',
                            'submodulename'=>'required|max:50|unique:submodules,submodulename'
                        ]);

                if ($validator->fails()) {
                    
                    Session::flash('error',"Submodule order and submodule name required !!");
                    return redirect()->back();
                }
            }
            else
            {
                $validator = Validator::make($request->all(), [
                           'submoduleorder'=>'required'
                        ]);

                if ($validator->fails()) {
                    
                    Session::flash('error',"Submodule order required !!");
                    return redirect()->back();
                }
            }
        }              
        
        //save into database
        $submodule->moduleid=$request->moduleid;
        $submodule->submodulename=$request->submodulename;
        $submodule->submoduleorder=$request->submoduleorder;
        $submodule->url=$request->submoduleurl;
        $submodule->update();

        //set flash data with success message
        Session::flash('msg', ' Sub Module updated successfully.');
        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\SubModule  $subModule
     * @return \Illuminate\Http\Response
     */
    public function destroy($submoduleid)
    {
        $submodule=SubModule::find($submoduleid);
        $submodule->delete();
        
        Session::flash('msg', ' Sub Module Deleted successfully.');
        return redirect()->back();
    }
}

resources/views/admin/submodules/index.blade.php
@extends('layouts.adminlayouts.app')
@section('content')
<!-- start page content -->
<div class="page-content-wrapper">
	<div class="page-content">
		<div class="page-bar">
			<div class="page-title-breadcrumb">
				<div class=" pull-left">
					<div class="page-title">SubModule Setup</div>
				</div>
				<ol class="breadcrumb page-breadcrumb pull-right">
					<li><a class="parent-item"
							href="/home"><i class="fa fa-home"></i></a>&nbsp;<i class="fa fa-angle-right"></i>
					</li>
					<li>Settings&nbsp;<i class="fa fa-angle-right"></i>
					</li>
					<li class="active">SubModules</li>
				</ol>
			</div>
		</div>
		<input type="hidden" name="" value="/admin/submodule" class="activeurl">
		<div class="row">
			<div class="col-md-12">
				<div class="card card-topline-green">
					<div class="card-head">
						<header>SubModule Setup</header>
						<div class="tools">
							<a class="fa fa-repeat btn-color box-refresh" href="javascript:;"></a>
							<a class="t-collapse btn-color fa fa-chevron-down"
								href="javascript:;"></a>
						</div>
					</div>
					<div class="card-body " id="savetoimage">
						
							@if (session('msg'))
		                        <div class="tstSuccess msg" style="display: none;">
		                            {{ session('msg') }}
		                        </div>
                    		@endif
                    		@if (session('error'))
		                        <div class="tstError error" style="display: none;">
		                            {{ session('error') }}
		                        </div>
                    		@endif
						<div class="row col-md-12">
							 <!-- Button trigger modal -->
							<button type="button" class="btn btn-circle btn-success" data-toggle="modal" data-target="#addsubmodule"><i class="fa fa-plus"></i> Add </button>
							<!-- Modal -->
							<div class="modal fade" id="addsubmodule" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
							  <div class="modal-dialog modal-dialog-centered" role="document">
							  	<form action="{{ route('submodule.store') }}" method="POST">
							  		@csrf
								   	<div class="modal-content card-box">
										<div class="modal-header">
											<header>Add SubModule</header>
										</div>
										<div class="card-body row form-body">
											<div class="col-lg-6 p-t-20">
												<label class="control-label" for="submodulename">SubModule Name</label>
												<select class="form-control" name="moduleid">
													<option selected disabled>Select SubModule Name</option>
													@foreach($modules as $module)
													<option value="{{ $module->moduleid }}">{{ $module->modulename }}</option>
													@endforeach
												</select>
											</div>
											<div class="col-lg-6 p-t-20">
												<div class="form-label-group">
													<label class="control-label" for="submodulename">SubModule Name
													</label>
													<input type="text" name="submodulename" id="submodulename" placeholder="enter submodule name" class="form-control" />
												</div>
											</div>
											<div class="col-lg-6 p-t-20">
												<div class="form-label-group">
													<label class="control-label" for="submoduleurl">SubModule URL
													</label>
													<input type="text" name="submoduleurl" id="submoduleurl" placeholder="enter submodule url" class="form-control" />
												</div>
											</div>
											<div class="col-lg-6 p-t-20">
												<div class="form-label-group">
													<label class="control-label" for="submoduleorder">SubModule Priority
													</label>
													<input type="number" name="submoduleorder" id="submoduleorder" placeholder="enter submodule priority" class="form-control" />
												</div>
											</div>
										</div>
										<div class="col-lg-12 p-t-20 p-b-20 text-center">
											<button type="button" class="btn btn-circle btn-secondary" data-dismiss="modal">Close</button>
								    		<button type="submit" class="btn btn-circle btn-success">Save changes</button>
										</div>
									</div>
								</form>
							  </div>
							</div>
							<!-- Modal Ends -->
						</div>
						<div class="table-scrollable ">
							<table class="table display" width="100%">
								<thead class="text-center">
									<tr>
										<th>S.N</th>
										<th>Module Name</th>
										<th>SubModule Name</th>
										<th>SubModule Priority</th>
										<th>SubModule url</th>
										<th>Action</th>
									</tr>
								</thead>
								<tbody>
									@php
									$i=1;
									@endphp
									@foreach($submodule as $submod)
									<tr class="text-center">
										<td>{{ $i++ }}</td>
										<td>{{ $submod->modulename }}</td>
										<td>{{ $submod->submodulename }}</td>
										<td>{{ $submod->submoduleorder }}</td>
										<td>{{ $submod->url }}</td>
										<td class="text-left">
											<!-- Button trigger modal -->
											<a href="" data-toggle="modal" data-target="#edit{{$submod->submoduleid}}">
												<i class="material-icons text-warning">edit</i>
											</a>
											<!-- Modal -->
											<div class="modal fade" id="edit{{ $submod->submoduleid }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
											  <div class="modal-dialog modal-dialog-centered" role="document">
											  	<form action="{{ url('admin/submodule/'.$submod->submoduleid) }}" method="POST">
											  		@csrf
											  		@method('put')
												   	<div class=" modal-content card-box">
												   		<div class="row">
														<div class="col-sm-12">
														<div class="modal-header">
															<header>Edit Module</header>
														</div>
														<div class="card-body row form-body text-left">
															<div class="col-lg-6 p-t-20">
																<label class="control-label" for="submodulename">SubModule Name</label>
																<select class="form-control" name="moduleid">
																	<option selected disabled>Select SubModule Name</option>
																	@foreach($modules as $module)
																	@if($module->moduleid == $submod->moduleid) 
																	<option selected value="{{ $module->moduleid }}">{{ $module->modulename }}</option>
																	@endif
																	@endforeach
																</select>
															</div>
															<div class="col-lg-6 p-t-20">
																<div class="form-label-group">
																	<label class="control-label" for="submodulename">SubModule Name
																	</label>
																	<input type="text" name="submodulename" id="submodulename" placeholder="enter submodule name" class="form-control" value="{{ old('submodulename',$submod->submodulename) }}" />
																</div>
															</div>
															<div class="col-lg-6 p-t-20">
																<div class="form-label-group">
																	<label class="control-label" for="submoduleurl">SubModule URL
																	</label>
																	<input type="text" name="submoduleurl" id="submoduleurl" placeholder="enter submodule url" class="form-control" value="{{ old('url',$submod->url) }}"/>
																</div>
															</div>
															<div class="col-lg-6 p-t-20">
																<div class="form-label-group">
																	<label class="control-label" for="submoduleorder">SubModule Priority
																	</label>
																	<input type="number" name="submoduleorder" id="submoduleorder" placeholder="enter submodule priority" class="form-control" value="{{ old('submoduleorder',$submod->submoduleorder) }}"/>
																</div>
															</div>
														</div>
														<div class="col-lg-12 p-t-20 p-b-20 text-center">
															<button type="button" class="btn btn-circle btn-secondary" data-dismiss="modal">Close</button>
												    		<button type="submit" class="btn btn-circle btn-success">Update changes</button>
														</div>
														</div>
														</div>
													</div>
												</form>
											  </div>
											</div>
											<!-- Modal Ends -->
											<a href="" data-toggle="modal" data-target="#delete{{$submod->submoduleid}}">
												<i class="material-icons text-danger">delete</i>
											</a>
											<!-- Modal -->
											<div class="modal fade" id="delete{{ $submod->submoduleid }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
											  <div class="modal-dialog modal-dialog-centered" role="document">
											  	<form action="{{ url('admin/submodule/'.$submod->submoduleid) }}" method="POST">
											  		@csrf
											  		@method('delete')
												   	<div class=" modal-content card-box text-center">
												   		<div class="row">
														<div class="col-sm-12">
														<div class="card-head">
															<header>Delete Module</header>
														</div>
														<div class="card-body row ml-5">
															<h3 class="text-white">Do you want to delete {{$submod->modulename}} Module??</h3>
															<h4 class="text-white">Can't Revert it!!!</h4>
														</div>
														<div class="col-lg-12 p-t-20 p-b-20 text-center">
															<button type="button" class="btn btn-circle btn-secondary" data-dismiss="modal">Close</button>
												    		<button type="submit" class="btn btn-circle btn-danger">Delete</button>
														</div>
														</div>
														</div>
													</div>
												</form>
											  </div>
											</div>
											<!-- Modal Ends -->
										</td>
									</tr>
									@endforeach
								</tbody>
							</table>
							{{ $submodule->links() }}
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- end page content -->
@endsection