routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use Illuminate\Foundation\Auth\AuthenticatesUsers;

//for admin controller
Route::get('/login', function () {
    return view('/auth/login');
});


Auth::routes(['verify' => true]);

Route::get('/home', 'HomeController@index')->name('home')->middleware('verified');
Route::post('/sendSMS','SendSMSController@store')->middleware('auth')->middleware('verified');
Route::post('/getBalance','SendSMSController@getBalance')->middleware('auth')->middleware('verified');
Route::get('/demo','DemoController@index')->middleware('auth')->middleware('verified');
Route::prefix('/admin')->middleware(['auth','verified'])->group(function () {
	Route::resource('/module','ModuleController',['expect'=>['show']]);
	Route::resource('/submodule','SubModuleController');
	Route::resource('/organizationdetail','OrganizationDetailController');
	Route::resource('/menusetup','MenuSetupController');
	Route::resource('/submenusetup','SubMenuSetupController');
	Route::resource('/usersetup', 'UserSetupController');
	Route::get('/changepassword/create','UserSetupController@changepasswordcreate');
	Route::get('/changepassword','UserSetupController@changepassword')->name('usersetup.changepassword');
	Route::resource('/footercontactsetup','FooterContactSetupController');
	Route::resource('/quicklinksetup','QuickLinkSetupController');
	Route::resource('/socialmediaicon','SocialMediaIconController');
	Route::resource('/slidersetup','SliderSetupController');
	Route::resource('/noticesetup','NoticeSetupController');
	Route::resource('/aboutus','AboutUsController');
	Route::resource('/service','ServiceController');
	Route::resource('/counter','CounterSetupController');
	Route::resource('/timetable','TimeTableController');
	Route::resource('/membermessage','MemberSetupController');
	Route::resource('/eventsetup','EventSetupController');
	Route::resource('/partner','PartnerController');
	Route::resource('/gallery','GalleryController');
	Route::resource('/testimonial','TestimonialController');
	Route::get('/gallery/album/{id}','GalleryController@intoAlbum');
	Route::post('/gallery/upload/store','GalleryController@fileStore')->name('users.fileupload');
	Route::get('/image/delete','GalleryController@fileDestroy');
	Route::get('/delete/image/{id}/{albumid}','GalleryController@deleteImage');
	Route::resource('/class','ClassesController');
	Route::resource('/section','SectionController');
	Route::resource('/subject','SubjectController');
	Route::resource('/lessonentity','LessonEntityController');
	Route::resource('/lessondetail','LessondetailController');
	Route::resource('/lesson','LessonController');
	Route::get('/getsubject','LessonController@getsubject');
	Route::get('/getlesson','LessonController@getlesson');
	Route::resource('/student','StudentController');
	Route::get('/getsection','StudentController@getsection');
});


//for frontend controller
Route::get('/','FrontEndController@index');
Route::get('/aboutus','FrontEndController@aboutus');
Route::get('/classes','FrontEndController@classes');
Route::get('/classes-timetable','FrontEndController@classestimetable');
Route::get('/services','FrontEndController@services');
Route::get('/ourteam','FrontEndController@ourteam');
Route::get('/contact','FrontEndController@contact');
Route::post('/contact','FrontEndController@sendmail');
Route::get('/ourblog','FrontEndController@ourblog');
Route::get('/gallery','FrontEndController@gallery');
Route::get('/bmi-calculator','FrontEndController@bmicalculator');
Route::post('/testimonial','FrontEndController@testimonial');

app/Http/Controllers/UserSetupController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Hash;
use Image;
use Validator;
use App\User;
use App\UserModule;
use App\UserSubModule;
use App\UserAccessLevel;
Use Session;
use DB;
use Auth;


class UserSetupController extends Controller
{
    public function __construct()
    {
       $this->middleware(['auth', 'verified']);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
       return view('admin.usersetup.index');
    }

    public function create()
    {
        return view('admin.usersetup.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //return $request->all();
        $validator = Validator::make($request->all(),[
            'name' => 'required|max:50',
            'password'  => 'required|max:50',
            'useremail' =>  'required|email|unique:users,email',
            'contactno' =>  'required|numeric',
            'expirydate'    =>  'required'
        ]);

        $user = new User;
        if($validator->passes())
        {
            $maxid =   getMaxId('users', 'id');
            $user->id = $maxid;
            $user->name = $request->name;
            $user->password = Hash::make($request->password);
            $user->email = $request->useremail;
            $user->contactno = $request->contactno;
            $user->expirydate = $request->expirydate;
            $image = $request->file( 'image' );
            if($image!=null)
            {
                $imageType = $image->getClientOriginalExtension();
                $imageStr =  (string) Image::make( $image )->resize( 200, null, function ( $constraint ) {
                                                 $constraint->aspectRatio();
                                                })->encode( $imageType );
                $user->image= base64_encode( $imageStr );
            } 
            $user->save(); 

    //first delete the selected checkbox and then again save it
        DB::table('usermodules')->where('id', $id)->delete();
        DB::table('usersubmodules')->where('id',$id)->delete();
        DB::table('useraccesslevels')->where('id',$id)->delete();  
    // To save the module which are ticked from checkbox
           
        $user->modules()->sync($request->modules,false);
    // To save the submodule which are ticked from checkbox

       $user->submodules()->sync($request->submodules,false);

    // To save the accesslevel which are ticked from checkbox
        $user->accesslevels()->sync($request->accesslevel,false);

            Session::flash('success', 'New User Added Successfully !!!');
            return redirect()->route('usersetup.index');
        }
        else
        {
            Session::flash('error',"Email should be Unique !!");
            return redirect()->route('usersetup.index');
        }
    }

    public function edit($id)
    {
        $user = User::find($id);

        $usermodule = DB::Table("modules")
        ->select("modules.*",
        DB::raw("(select id from usermodules where usermodules.moduleid = modules.moduleid and usermodules.id = ".$id.")as id"))->orderby('moduleid')->get(); 

        $usersubmodule = DB::Table("submodules")
        ->select("submodules.*",
        DB::raw("(select id from usersubmodules where submodules.submoduleid = usersubmodules.submoduleid and usersubmodules.id=".$id.")as id"))->orderby('submoduleid')->get();
        
        $useraccesslevel=DB::Table("accesslevels")
        ->select("accesslevels.*",
        DB::raw("(select id from useraccesslevels where accesslevels.accesslevelid = useraccesslevels.accesslevelid and useraccesslevels.id=".$id.")as id"))->orderby('accesslevelid')->get();

        return view('admin/usersetup/edit',compact('user','usermodule','usersubmodule','useraccesslevel'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //return $request->all();
        $validator = Validator::make($request->all(),[
            'name' => 'required|max:50',
            'useremail' =>  'required|email',
            'contactno' =>  'required|numeric',
            'expirydate'    =>  'required'
        ]);
        if($validator->passes())
        {
            $user = User::find($id);
            $user->name = $request->name;
            $user->email = $request->useremail;
            $user->contactno = $request->contactno;
            $user->expirydate = $request->expirydate;
            $image = $request->file( 'image' );
            if($image!=null)
            {
                $imageType = $image->getClientOriginalExtension();
                $imageStr =  (string) Image::make( $image )->
                                         resize( 200, null, function ( $constraint ) {
                                             $constraint->aspectRatio();
                                         })->encode( $imageType );
                $user->image= base64_encode( $imageStr );
            } 
            $user->save();   

    //first delete the selected checkbox and then again save it
        DB::table('usermodules')->where('id', $id)->delete();
        DB::table('usersubmodules')->where('id',$id)->delete();
        DB::table('useraccesslevels')->where('id',$id)->delete();

    // To save the module which are ticked from checkbox
        $user->modules()->sync($request->modules,false);
        
    // To save the submodule which are ticked from checkbox
        $user->submodules()->sync($request->submodules,false);

    // To save the accesslevel which are ticked from checkbox
        $user->accesslevels()->sync($request->accesslevel,false);

            Session::flash('success', "User Updated Successfully !!!");
            return redirect()->route('usersetup.index');
        }
        else
        {
            Session::flash('error',"Invalid Input Fields !!!");
            return redirect()->route('usersetup.index');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        DB::table('users')->where('id', $id)->delete();
        DB::table('usermodules')->where('id', $id)->delete();
        DB::table('usersubmodules')->where('id',$id)->delete();
        DB::table('useraccesslevels')->where('id',$id)->delete();

        Session::flash('success', 'User Deleted successfully.');
        return redirect()->route('usersetup.index');
    }

    public function changepasswordcreate()
    {
        return view('admin.usersetup.changepassword');
    }

    public function changepassword(Request $request)
    {

          $this->validate($request, array(
                'oldpassword' => 'required',
                'password' => 'required|confirmed'    
           
        ));

        $oldpassword = $request->get('oldpassword');
        $password = $request->get('password');
        
        if(!Hash::check($oldpassword, Auth::user()->password))
        {
            Session::flash('error', 'Old Password is incorrect');
       
            return redirect()->back();
        }

        $user = User::find(Auth::user()->id);
        // $user->password = bcrypt($password);
        $user->password=Hash::make($password);
        $user->save();
         Session::flash('success', 'Password has been changed successfully');
        return redirect('/login');
    
    }
}

resources/views/admin/usersetup/changepassword.blade.php
@extends('layouts.adminlayouts.app')
@section('content')
<!-- start page content -->
<div class="page-content-wrapper">
	<div class="page-content">
		<div class="page-bar">
			<div class="page-title-breadcrumb">
				<div class=" pull-left">
					<div class="page-title">Change Password</div>
				</div>
				<ol class="breadcrumb page-breadcrumb pull-right">
					<li><a class="parent-item"
							href="/home"><i class="fa fa-home"></i></a>&nbsp;<i class="fa fa-angle-right"></i>
					</li>
					<li class="active">Change Password</li>
				</ol>
			</div>
		</div>
		<div class="row">
			<div class="col-md-12">
				<div class="card card-topline-green">
					<div class="card-head">
						<header>Change Password</header>
						<div class="tools">
							<a class="fa fa-repeat btn-color box-refresh" href="javascript:;"></a>
							<a class="t-collapse btn-color fa fa-chevron-down"
								href="javascript:;"></a>
						</div>
					</div>
					<div class="card-body " id="savetoimage">
						@if (session('msg'))
	                        <div class="tstSuccess msg" style="display: none;">
	                            {{ session('msg') }}
	                        </div>
	            		@endif
	            		@if (session('error'))
	                        <div class="tstError error" style="display: none;">
	                            {{ session('error') }}
	                        </div>
	            		@endif
	            		<form action="{{ route('usersetup.changepassword') }}" method="GET">
	            			@csrf
	            		<label> Old Password : </label>
						<input class = 'form-control' type = 'password' name = 'oldpassword' required/>
						<label>New Password : </label>
						<input class = 'form-control' type = 'password' name = 'password' id='password'required />
						<label>Confirm Password : </label>
						<input class = 'form-control' type = 'password' name = 'password_confirmation' id='password_confirmation' required />
						<div id='message'></div>
						<br>
						<input type = 'submit' class = 'btn btn-success'  value="Save" />
					 </form>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- end page content -->
@endsection
@section('script')
<script type="text/javascript">

$('#password_confirmation').on('keyup', function () {
          //console.log($('#password').val()+'working');
	if(($('#password').val()).length!= 0)
	{
	  if ( $('#password_confirmation').val()== $('#password').val()) 
	  {
	    $('#message').html('Password Match').css('color', 'green');
	  } 
	  else
	  {
	    $('#message').html('Password Does Not Match').css('color', 'red');
	  } 
    }
    else
    {
      document.getElementById('message').innerHTML='';
    }
});
</script>
@endsection

resources/views/admin/usersetup/create.blade.php
@extends('layouts.adminlayouts.app')
@section('content')
<!-- start page content -->
<div class="page-content-wrapper">
	<div class="page-content">
		<div class="page-bar">
			<div class="page-title-breadcrumb">
				<div class=" pull-left">
					<div class="page-title">User Setup</div>
				</div>
				<ol class="breadcrumb page-breadcrumb pull-right">
					<li><a class="parent-item"
							href="/home"><i class="fa fa-home"></i></a>&nbsp;<i class="fa fa-angle-right"></i>
					</li>
					<li>Settings&nbsp;<i class="fa fa-angle-right"></i>
					</li>
					<li class="active">User Setup</li>
				</ol>
			</div>
		</div>
		<input type="hidden" name="" value="/admin/usersetup" class="activeurl">
		<div class="row">
			<div class="col-md-12">
				<div class="card card-topline-green">
					<div class="card-head">
						<header>User Detail</header>
						<div class="tools">
							<a class="fa fa-repeat btn-color box-refresh" href="javascript:;"></a>
							<a class="t-collapse btn-color fa fa-chevron-down"
								href="javascript:;"></a>
						</div>
					</div>
					<div class="card-body">
					  	<form action="{{ route('usersetup.store') }}" method="POST" enctype="multipart/form-data">
					  		@csrf
					  		<div class="row">
					  			<div class="pull-left col-lg-6">
					  				<div class="card">
					  					<div class="card-header d-flex justify-content-between">
					                        <div class="header-title">
					                           <h4 class="card-title">User Information</h4>
					                        </div>
					                     </div>
					                     <div class="card-body row form-body">
											<div class="col-lg-12 p-t-20">
												<label class="control-label" for="name">Full Name</label>
												<input type="text" name="name" id="name" placeholder="Enter Full Name" class="form-control" required="" />
											</div>
											<div class="col-lg-12 p-t-20">
												<div class="form-label-group">
													<label class="control-label" for="useremail">Email
													</label>
													<input type="email" name="useremail" id="useremail" placeholder="abc@____.com" class="form-control" required=""/>
												</div>
											</div>
											<div class="col-lg-12 p-t-20">
												<div class="form-label-group">
													<label class="control-label" for="password">Password
													</label>
													<input type="password" name="password" id="password" placeholder="Enter Password" class="form-control password" required=""/>
												</div>
											</div>
											<div class="col-lg-12 p-t-20">
												<div class="form-label-group">
													<label class="control-label" for="confirmpassword">Confirm Password
													</label>
													<input type="password" name="confirmpassword" id="confirmpassword" placeholder="Enter Confirm Password" class="form-control confirmpassword" required=""/>
													<div class="confirmpassword_error text-danger"></div>
													<div class="confirmpassword_success text-success"></div>
												</div>
											</div>
											<div class="col-lg-12 p-t-20">
												<div class="form-label-group">
													<label class="control-label" for="contactno">Contact Number
													</label>
													<input type="text" name="contactno" id="contactno" placeholder="Enter Contact number" class="form-control" pattern="-?[0-9]*(\.[0-9]+)?" required=""/>
												</div>
											</div>
											<div class="col-lg-12 p-t-20">
												<div class="form-label-group">
													<label class="control-label" for="expirydate">Expiry Date
													</label>
													<input type="date" name="expirydate" id="expirydate" placeholder="Enter Expiry Date" class="form-control" required=""/>
												</div>
											</div>
											<div class="row col-lg-12 p-t-20">
												<div class="col-lg-8"> 
													<div class="form-label-group">
														<label class="control-label" for="image">User Image
														</label>
														<input type="file" name="image" id="image" class="image form-control" required="">
													</div>
												</div>
												<div class="col-lg-12"> 
													<div class="form-label-group">
														<img src="" class="imgs" height="100" width="150">
													</div>
												</div>
											</div>
										</div>
					  				</div>
					  			</div>
					  			<div class="pull-right col-lg-6">
					  				<div class="card">
										<div class="card-header d-flex justify-content-between">
					                        <div class="header-title">
					                           <h4 class="card-title">User Access</h4>
					                        </div>
					                    </div>					  					 
				                        <div class="card-body row form-body">
				                        	<div class="col-lg-7">
				                        		<div class="modal-header">
													<header>Access Level</header>
												</div>
				                        		<div class="checkboxes p-t-20">
													@foreach ($module as $mod)
													<ul>
														<li>
															<input type='checkbox' name="modules[]" value="{{ $mod->moduleid }}" class="parent" /> {{ $mod->modulename }}
															@foreach ($submodules as $submodule)
															<ul>
																@if ( $mod->moduleid == $submodule->moduleid)
																<li>
																	<input type='checkbox' name="submodules[]" class='child' value="{{ $submodule->submoduleid }}" /> {{ $submodule->submodulename }}
																</li>
																@endif
															</ul>
															@endforeach
														</li>
													</ul>
													@endforeach
												</div>
				                        	</div>
				                        	<div class="col-lg-5">
												<div class="modal-header">
													<header>Access Level</header>
												</div>
												<div class="checkebox p-t-20">
													<ul>
														@foreach ($accesslevels as $access)
														<li>
															<input type="checkbox" name="accesslevel[]" value="{{ $access->accesslevelid }}" class="checkbox"> {{ $access->accesslevel }}
														</li>
														@endforeach
													</ul>
												</div>
											</div>
				                        </div>
					  				</div>
					  			</div>
								<div class="col-lg-12 p-t-20 p-b-20 text-center">
						    		<button type="submit" class="btn btn-circle btn-success save">Save changes</button>
								</div>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- end page content -->
@endsection
@section('script')

<script type="text/javascript">
	function preview(input){
		if(input.files && input.files[0]){
			var reader = new FileReader();
			reader.onload = function(e){
				$('.imgs').attr('src', e.target.result);
			}
			reader.readAsDataURL(input.files[0]);
			}
	}
	$('.image').change(function(){
		preview(this);
	})
</script>
<script type="text/javascript">
$(document).ready(function(){
	$(document).on('keyup','.confirmpassword',function(){
		var password=$('.password').val();
		var confirmpassword=$('.confirmpassword').val();
		console.log(password.toUpperCase() )
		console.log(confirmpassword.toUpperCase())
		if(password.toUpperCase() != confirmpassword.toUpperCase())
		{
			$('.confirmpassword_error').html("Password doesnot Matched!!!");
			$('.confirmpassword_success').html(" ");
            $('.save').attr('disabled',true);
		}
		else
		{
			$('.confirmpassword_success').html("Password Matched!!!");
			$('.confirmpassword_error').html(" ");
            $('.save').attr('disabled',false);
		}
	})
})
</script>
<script>
$('.checkbox').click(function(){
    $('.checkbox').each(function(){
        $(this).prop('checked', false); 
    }); 
    $(this).prop('checked', true);
});

$('input[type="checkbox"]').change(function(e) {
  var checked = $(this).prop("checked"),
      container = $(this).parent(),
      siblings = container.siblings();
  container.find('input[type="checkbox"]').prop({
    indeterminate: false,
    checked: checked
  });
  function checkSiblings(el) {
    var parent = el.parent().parent(),
        all = true;
    el.siblings().each(function() {
      return all = ($(this).children('input[type="checkbox"]').prop("checked") === checked);
    });
    console.log(all);
    if (all && checked) {
      parent.children('input[type="checkbox"]').prop({
        indeterminate: false,
        checked: checked
      });
      checkSiblings(parent);
    } else if (all && !checked) {
      parent.children('input[type="checkbox"]').prop("checked", checked);
      parent.children('input[type="checkbox"]').prop("checked", (parent.find('input[type="checkbox"]:checked').length > 0));
      checkSiblings(parent);
    } else {
      el.parents("li").children('input[type="checkbox"]').prop({
        indeterminate: true,
        checked: true
      });
    }
  }
  checkSiblings(container);
});
</script>
@endsection

resources/views/admin/usersetup/index.blade.php
@extends('layouts.adminlayouts.app')
@section('content')
<!-- start page content -->
<div class="page-content-wrapper">
	<div class="page-content">
		<div class="page-bar">
			<div class="page-title-breadcrumb">
				<div class=" pull-left">
					<div class="page-title">User Setup</div>
				</div>
				<ol class="breadcrumb page-breadcrumb pull-right">
					<li><a class="parent-item"
							href="/home"><i class="fa fa-home"></i></a>&nbsp;<i class="fa fa-angle-right"></i>
					</li>
					<li>Settings&nbsp;<i class="fa fa-angle-right"></i>
					</li>
					<li class="active">User Setup</li>
				</ol>
			</div>
		</div>
		<input type="hidden" name="" value="/admin/usersetup" class="activeurl">
		<div class="row">
			<div class="col-md-12">
				<div class="card card-topline-green">
					<div class="card-head">
						<header>User Detail</header>
						<div class="tools">
							<a class="fa fa-repeat btn-color box-refresh" href="javascript:;"></a>
							<a class="t-collapse btn-color fa fa-chevron-down"
								href="javascript:;"></a>
						</div>
					</div>
					<div class="card-body">
							@if(session('success'))
		                        <div class="tstSuccess msg" style="display: none;">
		                            {{ session('success') }}
		                        </div>
                    		@endif
                    		@if(session('error'))
		                        <div class="tstError error" style="display: none;">
		                            {{ session('error') }}
		                        </div>
                    		@endif
						<div class="row col-md-12">
							<a href="{{ route('usersetup.create') }}"><button type="button" class="btn btn-circle btn-success"><i class="fa fa-plus"></i> Add </button></a>
						</div>
						<div class="table-scrollable ">
							<table class="table display" width="100%">
								<thead class="text-center">
									<tr>
										<th>Name</th>
										<th>Email</th>
										<th>Phone</th>
										<th>Expiry Date</th>
										<th>Image</th>
										<th>Action</th>
									</tr>
								</thead>
								<tbody>
									@foreach($users as $user)
									<tr class="text-center">
										<td>{{ $user->name }}</td>
										<td>{{ $user->email }}</td>
										<td>{{ $user->contactno }}</td>
										<td>{{ $user->expirydate }}</td>
										<td><object data="{{'data:image/jpg;base64,'.$user->image}}" style="height:80px;width:130px"></object></td>
										<td class="text-left">
											<!-- Button trigger modal -->
											<a href="{{ url('admin/usersetup/'.$user->id.'/edit') }}">
												<i class="material-icons text-warning">edit</i>
											</a>
											<a href="" data-toggle="modal" data-target="#delete{{$user->id}}">
												<i class="material-icons text-danger">delete</i>
											</a>
											<!-- Modal -->
											<div class="modal fade" id="delete{{ $user->id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
											  <div class="modal-dialog modal-dialog-centered" role="document">
											  	<form action="{{ url('admin/usersetup/'.$user->id) }}" method="POST">
											  		@csrf
											  		@method('delete')
												   	<div class=" modal-content card-box">
												   		<div class="row">
														<div class="col-sm-12">
														<div class="card-head">
															<header>Delete User</header>
														</div>
														<div class="card-body row ml-5">
															<h4 class="text-white">Do you want to delete {{$user->name}}??</h4>
															<h4 class="text-white">Can't Revert it!!!</h4>
														</div>
														<div class="col-lg-12 p-t-20 p-b-20 text-center">
															<button type="button" class="btn btn-circle btn-secondary" data-dismiss="modal">Close</button>
												    		<button type="submit" class="btn btn-circle btn-danger">Delete</button>
														</div>
														</div>
														</div>
													</div>
												</form>
											  </div>
											</div>
											<!-- Modal Ends -->
										</td>
									</tr>
									@endforeach
								</tbody>
							</table>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- end page content -->
@endsection
@section('script')

@endsection